/**
 * SARS SIC7 industry codes (5-digit sub-classes) accepted on the employer reconciliation,
 * from SARS_PAYE_BRS - PAYE Employer Reconciliation V25.3.0 (June 2026), Appendix C.
 * Generated from the BRS; do not edit by hand. Appendix D (codes that do not qualify for
 * ETI) and Appendix E (special economic zones) follow.
 *
 * The copies in src/lib and supabase/functions/_shared must stay identical (a unit test compares them).
 */

export const SIC7_BRS_VERSION = 'V25.3.0';

export const SIC7_CODES: ReadonlyArray<readonly [code: string, description: string]> = [
  ["01110", "Growing of cereals (except rice), leguminous crops and oil seeds"],
  ["01120", "Growing of rice"],
  ["01130", "Growing of vegetables and melons, roots, and tubers"],
  ["01140", "Growing of sugar cane"],
  ["01150", "Growing of tobacco"],
  ["01160", "Growing of fibre crops"],
  ["01190", "Growing of other non-perennial crops"],
  ["01210", "Growing of grapes"],
  ["01220", "Growing of tropical and subtropical fruits"],
  ["01230", "Growing of citrus fruits"],
  ["01240", "Growing of pome fruits and stone fruits"],
  ["01250", "Growing of other tree and bush fruits and nuts"],
  ["01260", "Growing of oleaginous fruits"],
  ["01270", "Growing of beverage crops"],
  ["01280", "Growing of spices, aromatic, drug, and pharmaceutical crops"],
  ["01290", "Growing of other perennial crops"],
  ["01300", "Plant propagation"],
  ["01410", "Raising of cattle and buffaloes"],
  ["01420", "Raising of horses and other equines"],
  ["01430", "Raising of camels and camelids"],
  ["01440", "Raising of sheep and goats"],
  ["01450", "Raising of swine/pigs"],
  ["01460", "Raising of poultry"],
  ["01490", "Raising of other animals"],
  ["01500", "Mixed farming"],
  ["01610", "Support activities for crop production"],
  ["01620", "Support activities for animal production"],
  ["01630", "Post-harvest crop activities"],
  ["01640", "Seed processing for propagation"],
  ["01700", "Hunting, trapping and related service activities"],
  ["02100", "Silviculture and other forestry activities"],
  ["02200", "Logging"],
  ["02300", "Gathering of non-wood forest products"],
  ["02400", "Support services to forestry"],
  ["03110", "Marine fishing"],
  ["03120", "Freshwater fishing"],
  ["03210", "Marine aquaculture"],
  ["03220", "Freshwater aquaculture"],
  ["05100", "Mining of hard coal"],
  ["05200", "Mining of lignite"],
  ["06100", "Extraction of crude petroleum"],
  ["06200", "Extraction of natural gas"],
  ["07100", "Mining of iron ores"],
  ["07210", "Mining of uranium and thorium ores"],
  ["07291", "Mining of gold"],
  ["07292", "Mining of chrome"],
  ["07293", "Mining of copper"],
  ["07294", "Mining of manganese"],
  ["07295", "Mining of platinum group metals"],
  ["07299", "Other mining of non-ferrous metal ores n.e.c."],
  ["08101", "Quarrying of dimension stone"],
  ["08102", "Quarrying of limestone and lime works"],
  ["08109", "Other quarrying of stone, sand, and clay"],
  ["08911", "Mining of phosphates"],
  ["08919", "Other mining of chemical and fertilizer minerals"],
  ["08920", "Extraction of peat"],
  ["08930", "Extraction of salt"],
  ["08991", "Mining of diamonds"],
  ["08992", "Mining of precious and semi-precious stones, except diamonds"],
  ["08999", "Other mining and quarrying n.e.c."],
  ["09100", "Support activities for petroleum and natural gas extraction"],
  ["09901", "Service activities incidental to mining of minerals on a fee or contract basis"],
  ["09909", "Other support activities for other mining and quarrying n.e.c."],
  ["10101", "Slaughtering, dressing, and packing of livestock, including poultry and small game for meat"],
  ["10102", "Manufacture of prepared and preserved meat, including sausage; by-products (hides, bones, etc.)"],
  ["10103", "Production of lard and other edible fats"],
  ["10109", "Other processing and preserving of meat"],
  ["10200", "Processing and preserving of fish, crustaceans, and molluscs"],
  ["10300", "Processing and preserving of fruit and vegetables"],
  ["10401", "Manufacture of crude oil and oilseed cake and meal"],
  ["10402", "Manufacture of compound cooking fats, margarine, and edible oils"],
  ["10501", "Processing of fresh milk"],
  ["10502", "Manufacture of butter and cheese"],
  ["10503", "Manufacture of ice cream and other edible ice (whether or not containing cream or chocolate)"],
  ["10504", "Manufacture of milk powder, condensed milk, and other edible milk products, e.g. ghee, casein, or lactose"],
  ["10611", "Manufacture of flour and grain mill products, including rice and vegetable milling; grain mill residues"],
  ["10612", "Manufacture of breakfast foods"],
  ["10620", "Manufacture of starches and starch products"],
  ["10710", "Manufacture of bakery products"],
  ["10720", "Manufacture of sugar"],
  ["10730", "Manufacture of cocoa, chocolate, and sugar confectionery"],
  ["10740", "Manufacture of macaroni, noodles, couscous, and similar farinaceous products"],
  ["10750", "Manufacture of prepared meals and dishes"],
  ["10791", "Manufacture of coffee, coffee substitutes and tea"],
  ["10792", "Manufacture of nut foods"],
  ["10799", "Manufacture of spices, condiments, vinegar, yeast, egg products, soups, and other food"],
  ["10800", "Manufacture of prepared animal feeds"],
  ["11010", "Distilling, rectifying, and blending of spirits"],
  ["11020", "Manufacture of wines"],
  ["11031", "Manufacture of malt liquors such as beer, ale, porter, and stout"],
  ["11032", "Manufacture of sorghum beer"],
  ["11033", "Manufacture of malt"],
  ["11040", "Manufacture of soft drinks; production of mineral waters and other bottled waters"],
  ["12000", "Manufacture of tobacco products"],
  ["13111", "Preparatory activities in respect of animal fibres, including washing, combing and"],
  ["13112", "Preparatory activities in respect of vegetable fibres"],
  ["13119", "Other preparation and spinning of textile fibres"],
  ["13120", "Weaving of textiles"],
  ["13130", "Finishing of textiles"],
  ["13910", "Manufacture of knitted and crocheted fabrics"],
  ["13921", "Manufacture of blankets, made-up furnishing articles and stuffed articles"],
  ["13922", "Manufacture of tents, tarpaulins, sails and other canvas goods and car seat covers"],
  ["13930", "Manufacture of carpets and rugs"],
  ["13940", "Manufacture of cordage, rope, twine, and netting"],
  ["13990", "Manufacture of other textiles n.e.c."],
  ["14100", "Manufacturing of wearing apparel, except fur apparel"],
  ["14200", "Manufacture of articles of fur"],
  ["14300", "Manufacture of knitted and crocheted apparel"],
  ["15110", "Tanning and dressing of leather; dressing and dyeing of fur"],
  ["15120", "Manufacture of luggage, handbags and the like, saddlery, and harness"],
  ["15200", "Manufacture of footwear"],
  ["16100", "Sawmilling and planing of wood"],
  ["16210", "Manufacture of veneer sheets and wood-based panels"],
  ["16220", "Manufacture of builders’ carpentry and joinery"],
  ["16230", "Manufacture of wooden containers"],
  ["16291", "Manufacture of other products of wood"],
  ["16292", "Manufacturing of other articles of cork, straw and plaiting materials, including"],
  ["17010", "Manufacture of pulp, paper, and paperboard"],
  ["17021", "Manufacture of corrugated paper and paperboard"],
  ["17022", "Manufacture of containers of paper and paperboard"],
  ["17090", "Manufacture of other articles of paper and paperboard"],
  ["18110", "Printing"],
  ["18120", "Service activities related to printing"],
  ["18200", "Reproduction of recorded media"],
  ["19100", "Manufacture of coke oven products"],
  ["19200", "Manufacture of refined petroleum products"],
  ["20110", "Manufacture of basic chemicals"],
  ["20120", "Manufacture of fertilizers and nitrogen compounds"],
  ["20130", "Manufacture of plastics and synthetic rubber in primary forms"],
  ["20210", "Manufacture of pesticides and other agrochemical products"],
  ["20220", "Manufacture of paints, varnishes and similar coatings, printing ink and mastics"],
  ["20230", "Manufacture of soap and detergents, cleaning and polishing preparations, perfumes and toilet preparations"],
  ["20291", "Manufacture of explosives and pyrotechnic products"],
  ["20292", "Manufacture of adhesives, glues, sizes, and cements"],
  ["20299", "Manufacture of other chemical products n.e.c."],
  ["20300", "Manufacture of man-made fibres"],
  ["21000", "Manufacture of pharmaceuticals, medicinal chemical, and botanical products"],
  ["22110", "Manufacture of rubber tyres and tubes; retreading and rebuilding of rubber tyres"],
  ["22190", "Manufacture of other rubber products"],
  ["22200", "Manufacture of plastic products"],
  ["23100", "Manufacture of glass and glass products"],
  ["23910", "Manufacture of refractory products"],
  ["23920", "Manufacture of clay building materials"],
  ["23930", "Manufacture of other porcelain and ceramic products"],
  ["23940", "Manufacture of cement, lime, and plaster"],
  ["23950", "Manufacture of articles of concrete, cement, and plaster"],
  ["23960", "Cutting, shaping, and finishing of stone"],
  ["23990", "Manufacture of other non-metallic mineral products n.e.c."],
  ["24101", "Basic iron and steel industries; except steel pipe and tube mills"],
  ["24102", "Steel pipe and tube mills"],
  ["24201", "Refining of precious metals, e.g. gold, silver, and platinum"],
  ["24202", "Manufacture of primary non-ferrous metal products, excluding precious metals"],
  ["24310", "Casting of iron and steel"],
  ["24320", "Casting of non-ferrous metals"],
  ["25111", "Manufacture of metal structures or parts thereof"],
  ["25119", "Manufacture of other structural metal products, e.g. metal doors, windows, and gates"],
  ["25120", "Manufacture of tanks, reservoirs, and containers of metal"],
  ["25130", "Manufacture of steam generators, except central heating hot water boilers"],
  ["25200", "Manufacture of weapons and ammunition"],
  ["25910", "Forging, pressing, stamping, and roll-forming of metal; powder metallurgy"],
  ["25921", "Treating and coating of metals"],
  ["25922", "General mechanical engineering on a fee or contract basis"],
  ["25930", "Manufacture of cutlery, hand tools and general hardware"],
  ["25991", "Manufacture of metal containers, e.g. cans and tins"],
  ["25992", "Manufacture of cables and wire products"],
  ["25993", "Manufacture of springs (all types)"],
  ["25994", "Manufacture of metal fasteners"],
  ["25999", "Other Manufacture of other fabricated metal products n.e.c."],
  ["26100", "Manufacture of electronic components and boards"],
  ["26200", "Manufacture of computers and peripheral equipment"],
  ["26300", "Manufacture of communication equipment"],
  ["26400", "Manufacture of consumer electronics"],
  ["26510", "Manufacture of measuring, testing, navigating and control equipment"],
  ["26520", "Manufacture of watches and clocks"],
  ["26600", "Manufacture of irradiation, electromedical and electrotherapeutic equipment"],
  ["26700", "Manufacture of optical instruments and photographic equipment"],
  ["26800", "Manufacture of magnetic and optical media"],
  ["27100", "Manufacture of electric motors, generators, transformers, and electricity distribution and control apparatus"],
  ["27200", "Manufacture of batteries and accumulators"],
  ["27310", "Manufacture of fibre optic cables"],
  ["27320", "Manufacture of other electronic and electric wires and cables"],
  ["27330", "Manufacture of wiring devices"],
  ["27400", "Manufacture of electric lighting equipment"],
  ["27500", "Manufacture of domestic appliances"],
  ["27900", "Manufacture of other electrical equipment"],
  ["28110", "Manufacture of engines and turbines, except aircraft, vehicle, and cycle engines"],
  ["28120", "Manufacture of fluid power equipment"],
  ["28130", "Manufacture of other pumps, compressors, taps and valves"],
  ["28140", "Manufacture of bearings, gears, gearing and driving elements"],
  ["28150", "Manufacture of ovens, furnaces, and furnace burners"],
  ["28160", "Manufacture of lifting and handling equipment"],
  ["28170", "Manufacture of office machinery and equipment (except computers and peripheral equipment)"],
  ["28180", "Manufacture of power-driven hand tools"],
  ["28190", "Manufacture of other general-purpose machinery"],
  ["28210", "Manufacture of agricultural and forestry machinery"],
  ["28220", "Manufacture of metal-forming machinery and machine tools"],
  ["28230", "Manufacture of machinery for metallurgy"],
  ["28240", "Manufacture of machinery for mining, quarrying and construction"],
  ["28250", "Manufacture of machinery for food, beverage, and tobacco processing"],
  ["28260", "Manufacture of machinery for textile, apparel, and leather production"],
  ["28290", "Manufacture of other special-purpose machinery"],
  ["29100", "Manufacture of motor vehicles"],
  ["29200", "Manufacture of bodies (coachwork) for motor vehicles; manufacture of trailers and semi-trailers"],
  ["29300", "Manufacture of parts and accessories for motor vehicles"],
  ["30110", "Building of ships and floating structures"],
  ["30120", "Building of pleasure and sporting boats"],
  ["30200", "Manufacture of railway locomotives and rolling stock"],
  ["30300", "Manufacture of air and spacecraft and related machinery"],
  ["30400", "Manufacture of military fighting vehicles"],
  ["30910", "Manufacture of motorcycles"],
  ["30920", "Manufacture of bicycles and invalid carriages"],
  ["30990", "Manufacture of other transport equipment n.e.c."],
  ["31000", "Manufacture of furniture"],
  ["32111", "Manufacture of jewellery and related articles composed of precious metals, precious and semi-precious stone and pearls"],
  ["32119", "Other precious and semi-precious stone cutting and polishing"],
  ["32120", "Manufacture of imitation jewellery and related articles"],
  ["32200", "Manufacture of musical instruments"],
  ["32300", "Manufacture of sports goods"],
  ["32400", "Manufacture of games and toys"],
  ["32500", "Manufacture of medical and dental instruments and supplies"],
  ["32901", "Manufacture of coffins"],
  ["32909", "Other manufacture n.e.c. (except coffins)"],
  ["33110", "Repair of fabricated metal products"],
  ["33120", "Repair of machinery"],
  ["33130", "Repair of electronic and optical equipment"],
  ["33140", "Repair of electrical equipment"],
  ["33150", "Repair of transport equipment, except motor vehicles"],
  ["33190", "Repair of other equipment"],
  ["33200", "Installation of industrial machinery and equipment"],
  ["35101", "Generation of electricity"],
  ["35102", "Distribution of purchased electric energy only"],
  ["35103", "Generation and/or distribution for own use"],
  ["35200", "Manufacture of gas; distribution of gaseous fuels through mains"],
  ["35300", "Steam and air conditioning supply"],
  ["36000", "Water collection, treatment, and supply"],
  ["37000", "Sewerage"],
  ["38110", "Collection of non-hazardous waste"],
  ["38120", "Collection of hazardous waste"],
  ["38210", "Treatment and disposal of non-hazardous waste"],
  ["38220", "Treatment and disposal of hazardous waste"],
  ["38300", "Materials recovery"],
  ["39000", "Remediation activities and other waste management services"],
  ["41000", "Construction of buildings"],
  ["42100", "Construction of roads and railways"],
  ["42200", "Construction of utility projects"],
  ["42900", "Construction of other civil engineering projects"],
  ["43110", "Demolition"],
  ["43120", "Site preparation"],
  ["43210", "Electrical installation"],
  ["43220", "Plumbing, heat, and air-conditioning installation"],
  ["43290", "Other construction installation"],
  ["43301", "Painting and decorating"],
  ["43302", "Shop fitting"],
  ["43309", "Other building and completion and finishing"],
  ["43901", "Rental of construction machinery and equipment (with operator)"],
  ["43909", "Other specialized construction activities n.e.c."],
  ["45101", "Wholesale of motor vehicles"],
  ["45102", "Retail of new motor vehicles"],
  ["45103", "Retail sale of used motor vehicles"],
  ["45200", "Maintenance and repair of motor vehicles"],
  ["45300", "Sale of motor vehicle parts and accessories"],
  ["45400", "Sale, maintenance and repair of motorcycles and related parts and accessories"],
  ["45500", "Retail of automotive fuel in specialized stores"],
  ["46100", "Wholesale on a fee or contract basis"],
  ["46200", "Wholesale of agricultural raw materials and live animals"],
  ["46301", "Wholesale trade in foodstuffs"],
  ["46302", "Wholesale trade in beverages"],
  ["46303", "Wholesale in tobacco products"],
  ["46410", "Wholesale of textiles, clothing, and footwear"],
  ["46491", "Wholesale trade in household furniture, requisites, and appliances"],
  ["46492", "Wholesale trade in books and stationery"],
  ["46493", "Wholesale trade in pharmaceuticals, toiletries, and medical equipment"],
  ["46499", "Other wholesale trade in other household goods n.e.c."],
  ["46510", "Wholesale of computers, computer peripheral equipment and software"],
  ["46520", "Wholesale of electronic and telecommunications equipment and parts"],
  ["46530", "Wholesale of agricultural machinery, equipment, and supplies"],
  ["46590", "Wholesale of other machinery and equipment"],
  ["46610", "Wholesale of solid, liquid, and gaseous fuels and related products"],
  ["46621", "Wholesale of gold"],
  ["46629", "Other wholesale of metals and metal ores"],
  ["46630", "Wholesale of construction materials, hardware, plumbing and heating equipment and supplies"],
  ["46691", "Sale of used parts and accessories, including scrapyards"],
  ["46692", "Wholesale trade in diamonds, pearls, and other precious and semi-precious stones"],
  ["46699", "Other wholesale of waste and scrap and other products n.e.c."],
  ["46900", "Non-specialised wholesale trade"],
  ["47110", "Retail sale in non-specialized stores with food, beverages or tobacco predominating"],
  ["47190", "Other retail sale in non-specialized stores"],
  ["47211", "Retail trade in fresh fruit and vegetables"],
  ["47212", "Retail in meat and meat products"],
  ["47213", "Retail trade in bakery products"],
  ["47219", "Other retail sale in specialised stores"],
  ["47220", "Retail sale of beverages in specialised stores"],
  ["47230", "Retail sale of tobacco products in specialised stores"],
  ["47310", "Retail sale of computers, peripheral units, software, and telecommunications"],
  ["47320", "Retail sale of audio and video equipment in specialised stores"],
  ["47410", "Retail sale of textiles in specialized stores"],
  ["47420", "Retail sale of hardware, paints, and glass in specialized stores"],
  ["47430", "Retail sale of carpets, rugs, wall, and floor coverings in specialized stores"],
  ["47490", "Retail sale of electrical household appliances, furniture, lighting equipment and other household articles in specialised stores"],
  ["47510", "Retail sale of books, newspapers, and stationery in specialized stores"],
  ["47520", "Retail sale of music and video recordings in specialized stores"],
  ["47530", "Retail sale of sporting equipment in specialized stores"],
  ["47540", "Retail sale of games and toys in specialized stores"],
  ["47610", "Retail sale of clothing, footwear, and leather articles in specialized stores"],
  ["47620", "Retail sale of pharmaceutical and medical goods, cosmetic and toilet articles in specialized stores"],
  ["47631", "Specialized retail sale of jewellery"],
  ["47632", "Specialized retail sale of watches and clocks"],
  ["47639", "Other retail sale of new goods in specialized stores n.e.c."],
  ["47640", "Retail sale of second-hand goods"],
  ["47710", "Retail sale via stalls and markets of food, beverages, and tobacco products"],
  ["47720", "Retail sale via stalls and markets of textiles, clothing, and footwear"],
  ["47790", "Retail sale via stalls and markets of other goods"],
  ["47810", "Retail sale via mail order houses or via internet"],
  ["47890", "Other retail sale not in stores, stalls, or markets"],
  ["49110", "Passenger rail transport, interurban"],
  ["49120", "Freight rail transport"],
  ["49210", "Urban and suburban passenger transport"],
  ["49221", "Minibus Taxi transport"],
  ["49222", "Other Taxi transport (except minibus taxis)"],
  ["49223", "Bus transport"],
  ["49229", "Other passenger land transport n.e.c."],
  ["49230", "Freight transport by road"],
  ["49300", "Transport via pipeline"],
  ["50110", "Sea and coastal passenger water transport"],
  ["50120", "Sea and coastal freight water transport"],
  ["50210", "Inland passenger water transport"],
  ["50220", "Inland freight water transport"],
  ["51100", "Passenger air transport"],
  ["51200", "Freight air transport"],
  ["52100", "Warehousing and storage"],
  ["52211", "Operation of parking garages and parking lots"],
  ["52212", "Operation of roads and toll roads"],
  ["52219", "Other service activities incidental to land transportation"],
  ["52220", "Service activities incidental to water transportation"],
  ["52230", "Service activities incidental to air transportation"],
  ["52240", "Cargo handling"],
  ["52290", "Other transportation support activities"],
  ["53100", "Postal activities"],
  ["53200", "Courier activities"],
  ["55101", "Short term accommodation activities of hotels and motels"],
  ["55102", "Short term accommodation activities of guesthouses, bed, and breakfast"],
  ["55103", "Short term accommodation activities of pensions, youth hostels and mountain refuges"],
  ["55109", "Short term accommodation activities of visitor flats and bungalows, time-share units and holiday homes and other accommodation"],
  ["55200", "Camping grounds, recreational vehicle parks and trailer parks"],
  ["55900", "Other accommodation"],
  ["56101", "Food service activities of take away counters"],
  ["56109", "Other restaurant and mobile food service activities"],
  ["56210", "Event catering"],
  ["56290", "Other food service activities"],
  ["56300", "Beverage serving activities"],
  ["58110", "Book publishing"],
  ["58120", "Publishing of directories and mailing lists"],
  ["58130", "Publishing of newspapers, journals, and periodicals"],
  ["58190", "Other publishing activities"],
  ["58200", "Software publishing"],
  ["59110", "Motion picture, video, and television programme production activities"],
  ["59120", "Motion picture, video, and television programme post-production activities"],
  ["59130", "Motion picture, video, and television programme distribution activities"],
  ["59140", "Motion picture projection activities"],
  ["59200", "Sound recording and music publishing activities"],
  ["60100", "Radio broadcasting"],
  ["60200", "Television programming and broadcasting activities"],
  ["61100", "Wired telecommunications activities"],
  ["61200", "Wireless telecommunications activities"],
  ["61300", "Satellite telecommunications activities"],
  ["61900", "Other telecommunications activities"],
  ["62010", "Computer programming activities"],
  ["62020", "Computer consultancy and computer facilities management activities"],
  ["62090", "Other information technology and computer service activities"],
  ["63110", "Data processing, hosting, and related activities"],
  ["63120", "Web portals"],
  ["63910", "News agency activities"],
  ["63990", "Other information service activities n.e.c."],
  ["64110", "Central banking"],
  ["64190", "Other monetary intermediation"],
  ["64200", "Activities of holding companies"],
  ["64300", "Trusts, funds, and similar financial entities"],
  ["64910", "Financial leasing"],
  ["64920", "Other credit granting"],
  ["64990", "Other financial service activities, except insurance and pension funding activities n.e.c."],
  ["65110", "Life insurance"],
  ["65121", "Health insurance"],
  ["65122", "Travel insurance"],
  ["65123", "Transport insurance"],
  ["65129", "Other non-life insurance"],
  ["65200", "Reinsurance"],
  ["65300", "Pension funding"],
  ["66110", "Administration of financial markets"],
  ["66120", "Security and commodity contracts brokerage"],
  ["66190", "Other activities auxiliary to financial service activities"],
  ["66210", "Risk and damage evaluation"],
  ["66220", "Activities of insurance agents and brokers"],
  ["66290", "Other activities auxiliary to insurance and pension funding"],
  ["66300", "Fund management activities"],
  ["68100", "Real estate activities with own or leased property"],
  ["68200", "Real estate activities on a fee or contract basis"],
  ["69100", "Legal activities"],
  ["69201", "Accounting and bookkeeping activities"],
  ["69202", "Auditing activities"],
  ["69209", "Other accounting, bookkeeping, and auditing activities, tax consultancy"],
  ["70100", "Activities of head offices"],
  ["70200", "Management consultancy activities"],
  ["71101", "Consulting engineering activities"],
  ["71102", "Architectural activities"],
  ["71103", "Activities of quantity surveyors"],
  ["71104", "Activities of land surveyors"],
  ["71105", "Geological and prospecting activities on a fee or contract basis"],
  ["71106", "Activities of non-registered architects, e.g. tracers and draughtsmen"],
  ["71109", "Other architectural and engineering activities and related technical consultancy"],
  ["71200", "Technical testing and analysis"],
  ["72100", "Research and experimental development on natural sciences and engineering"],
  ["72200", "Research and experimental development on social sciences and humanities"],
  ["73100", "Advertising"],
  ["73200", "Market research and public opinion polling"],
  ["74100", "Specialized design activities"],
  ["74200", "Photographic activities"],
  ["74900", "Other professional, scientific, and technical activities n.e.c."],
  ["75000", "Veterinary activities"],
  ["77100", "Renting and leasing of motor vehicles (without driver)"],
  ["77210", "Renting and leasing of recreational and sports goods"],
  ["77220", "Renting of video tapes and disks"],
  ["77290", "Renting and leasing of other personal and household goods"],
  ["77301", "Renting of land transport equipment"],
  ["77302", "Renting of water transport equipment"],
  ["77303", "Renting of air transport equipment"],
  ["77304", "Renting of agricultural machinery and equipment"],
  ["77305", "Renting of construction and civil engineering machinery and equipment"],
  ["77306", "Renting of office machinery and equipment"],
  ["77309", "Renting and leasing of other machinery, equipment, and tangible goods n.e.c."],
  ["77400", "Leasing of intellectual property and similar products, except copyrighted works"],
  ["78100", "Activities of employment placement agencies"],
  ["78200", "Temporary employment agency activities"],
  ["78300", "Other human resources provision"],
  ["79110", "Travel agency activities"],
  ["79120", "Tour operator activities"],
  ["79900", "Other reservation service and related activities"],
  ["80100", "Private security activities"],
  ["80200", "Security systems service activities"],
  ["80300", "Investigation activities"],
  ["81100", "Combined facilities support activities"],
  ["81210", "General cleaning of buildings"],
  ["81290", "Other building and industrial cleaning activities"],
  ["81300", "Landscape care and maintenance service activities"],
  ["82110", "Combined office administrative service activities"],
  ["82190", "Photocopying, document preparation and other specialized office support activities"],
  ["82200", "Activities of call centres"],
  ["82300", "Organization of conventions and trade shows"],
  ["82910", "Activities of collection agencies and credit bureaus"],
  ["82920", "Packaging activities"],
  ["82990", "Other business support service activities n.e.c."],
  ["84111", "General public administration at National Government level"],
  ["84112", "General public administration at Provincial Government level"],
  ["84113", "General public administration at Local Government level"],
  ["84121", "Regulation of the activities of providing health care, education, cultural services and other social services, excluding social security at National Government level"],
  ["84122", "Regulation of the activities of providing health care, education, cultural services and other social services, excluding social security at Provincial Government level"],
  ["84123", "Regulation of the activities of providing health care, education, cultural services and other social services, excluding social security at Local Government level"],
  ["84131", "Regulation of and contribution to more efficient operation of businesses at National Government level"],
  ["84132", "Regulation of and contribution to more efficient operation of businesses at Provincial Government level"],
  ["84133", "Regulation of and contribution to more efficient operation of businesses at Local Government level"],
  ["84140", "Extra budgetary account n.e.c."],
  ["84210", "Foreign affairs"],
  ["84220", "Defence activities"],
  ["84231", "Public order and safety activities at National Government level"],
  ["84232", "Public order and safety activities at Provincial Government level"],
  ["84233", "Public order and safety activities at Local Government level"],
  ["84300", "Compulsory social security activities"],
  ["85101", "Pre-primary education and activities of after-school centres"],
  ["85102", "Primary education"],
  ["85210", "General secondary education"],
  ["85220", "Technical and vocational secondary education"],
  ["85300", "Higher education"],
  ["85410", "Sports and recreation education"],
  ["85420", "Cultural education"],
  ["85490", "Other education n.e.c."],
  ["85500", "Educational support activities"],
  ["86100", "Hospital activities"],
  ["86201", "Medical practitioner- and specialist activities"],
  ["86202", "Dentist and specialist dentist activities"],
  ["86209", "Other medical and dental practice activities"],
  ["86900", "Other human health activities"],
  ["87100", "Residential nursing care facilities"],
  ["87200", "Residential care activities for mental retardation, mental health, and substance abuse"],
  ["87300", "Residential care activities for the elderly and disabled"],
  ["87900", "Other residential care activities"],
  ["88100", "Social work activities without accommodation for the elderly and disabled"],
  ["88900", "Other social work activities without accommodation"],
  ["90000", "Creative, arts and entertainment activities"],
  ["91010", "Library and archives activities"],
  ["91020", "Museums activities and operation of historical sites and buildings"],
  ["91030", "Botanical and zoological gardens and nature reserves activities"],
  ["92000", "Gambling and betting activities"],
  ["93110", "Operation of sports facilities"],
  ["93120", "Activities of sports clubs"],
  ["93190", "Other sports activities"],
  ["93210", "Activities of amusement parks and theme parks"],
  ["93290", "Other amusement and recreation activities n.e.c."],
  ["94110", "Activities of business and employers’ membership organizations"],
  ["94120", "Activities of professional membership organizations"],
  ["94200", "Activities of trade unions"],
  ["94910", "Activities of religious organizations"],
  ["94920", "Activities of political organizations"],
  ["94990", "Activities of other membership organizations n.e.c."],
  ["95110", "Repair of computers and peripheral equipment"],
  ["95120", "Repair of communication equipment"],
  ["95210", "Repair of consumer electronics"],
  ["95220", "Repair of household appliances and home and garden equipment"],
  ["95230", "Repair of footwear and leather goods"],
  ["95240", "Repair of furniture and home furnishings"],
  ["95290", "Repair of other personal and household goods"],
  ["96010", "Washing and (dry-) cleaning of textile- and fur products"],
  ["96021", "Hairdressing"],
  ["96022", "Beauty treatment"],
  ["96030", "Funeral and related activities"],
  ["96090", "Other personal service activities n.e.c."],
  ["97000", "Activities of households as employers of domestic personnel"],
  ["98100", "Undifferentiated goods-producing activities of private households for own use"],
  ["98200", "Undifferentiated service-producing activities of private households for own use"],
  ["99011", "Activities of extraterritorial organizations and bodies"],
  ["99012", "Representatives of foreign countries"],
  ["99013", "Not economically active people, beggars, people living from handouts and charity, etc."],
  ["99014", "Unemployed people, people seeking work, etc."],
];

/** Appendix D: employers in these industries cannot claim ETI. */
export const SIC7_NOT_QUALIFYING_FOR_ETI: ReadonlySet<string> = new Set([
  '84111', '84112', '84113', '84121', '84122', '84123', '84131', '84132', '84133',
  '84140', '84210', '84220', '84231', '84232', '84233', '84300',
]);

/** Appendix E: special economic zones, where the ETI age limit does not apply. */
export const ETI_SPECIAL_ECONOMIC_ZONES: ReadonlyArray<readonly [code: string, name: string]> = [
  ['COE', 'Coega SEZ'],
  ['DTP', 'Dube Trade Port SEZ'],
  ['EAL', 'East London SEZ'],
  ['MAP', 'Maluti-a-Phofung SEZ'],
  ['SLB', 'Saldanha Bay SEZ'],
  ['RIB', 'Richards Bay SEZ'],
];

const SIC7_SET = new Set(SIC7_CODES.map(([code]) => code));

export function isValidSic7Code(code: string | null | undefined): boolean {
  return !!code && SIC7_SET.has(code);
}
