/**
 * Platform rule catalogue — mirrors payroll_rule_catalog seed data.
 * Additional rules can be registered here without engine redesign.
 */

import type { PayrollRuleDefinition } from './types.ts';

export const PAYROLL_RULE_CATALOG: PayrollRuleDefinition[] = [
  {
    id: 'basic_salary',
    name: 'Basic Salary',
    category: 'earning',
    enabledByDefault: true,
    companyConfigurable: false,
    employeeConfigurable: false,
    calculationOrder: 10,
    employeeContribution: false,
    employerContribution: false,
    taxableImpact: 'taxable',
    accountingImpact: 'wages',
    version: '1.0.0',
    effectiveFrom: '2025-03-01',
    payslipLabel: 'Basic Salary',
    description: 'Base remuneration from employee salary record',
  },
  {
    id: 'pension',
    name: 'Pension Fund',
    category: 'benefit',
    enabledByDefault: false,
    companyConfigurable: true,
    employeeConfigurable: true,
    calculationOrder: 50,
    employeeContribution: true,
    employerContribution: false,
    taxableImpact: 'pre_tax_deduction',
    accountingImpact: 'employee_deduction',
    version: '1.0.0',
    effectiveFrom: '2025-03-01',
    payslipLabel: 'Pension',
  },
  {
    id: 'provident_fund',
    name: 'Provident Fund',
    category: 'benefit',
    enabledByDefault: false,
    companyConfigurable: true,
    employeeConfigurable: true,
    calculationOrder: 51,
    employeeContribution: true,
    employerContribution: false,
    taxableImpact: 'pre_tax_deduction',
    accountingImpact: 'employee_deduction',
    version: '1.0.0',
    effectiveFrom: '2025-03-01',
    payslipLabel: 'Provident Fund',
  },
  {
    id: 'medical_aid',
    name: 'Medical Aid',
    category: 'benefit',
    enabledByDefault: false,
    companyConfigurable: true,
    employeeConfigurable: true,
    calculationOrder: 52,
    employeeContribution: true,
    employerContribution: false,
    taxableImpact: 'pre_tax_deduction',
    accountingImpact: 'employee_deduction',
    version: '1.0.0',
    effectiveFrom: '2025-03-01',
    payslipLabel: 'Medical Aid',
  },
  {
    id: 'paye',
    name: 'PAYE',
    category: 'statutory',
    enabledByDefault: true,
    companyConfigurable: true,
    employeeConfigurable: false,
    calculationOrder: 100,
    employeeContribution: true,
    employerContribution: false,
    taxableImpact: 'none',
    accountingImpact: 'employee_deduction',
    version: '1.0.0',
    effectiveFrom: '2025-03-01',
    payslipLabel: 'PAYE',
    description: 'Pay-As-You-Earn income tax',
  },
  {
    id: 'uif',
    name: 'UIF (Employee)',
    category: 'statutory',
    enabledByDefault: true,
    companyConfigurable: true,
    employeeConfigurable: false,
    calculationOrder: 110,
    employeeContribution: true,
    employerContribution: false,
    taxableImpact: 'none',
    accountingImpact: 'employee_deduction',
    version: '1.0.0',
    effectiveFrom: '2025-03-01',
    payslipLabel: 'UIF',
  },
  {
    id: 'uif_employer',
    name: 'UIF (Employer)',
    category: 'statutory',
    enabledByDefault: true,
    companyConfigurable: true,
    employeeConfigurable: false,
    calculationOrder: 111,
    employeeContribution: false,
    employerContribution: true,
    taxableImpact: 'none',
    accountingImpact: 'employer_liability',
    version: '1.0.0',
    effectiveFrom: '2025-03-01',
    payslipLabel: 'UIF Employer',
  },
  {
    id: 'sdl',
    name: 'SDL',
    category: 'statutory',
    enabledByDefault: true,
    companyConfigurable: true,
    employeeConfigurable: false,
    calculationOrder: 112,
    employeeContribution: false,
    employerContribution: true,
    taxableImpact: 'none',
    accountingImpact: 'employer_expense',
    version: '1.0.0',
    effectiveFrom: '2025-03-01',
    payslipLabel: 'SDL',
  },
  {
    id: 'union_fees',
    name: 'Union Fees',
    category: 'deduction',
    enabledByDefault: false,
    companyConfigurable: true,
    employeeConfigurable: true,
    calculationOrder: 120,
    employeeContribution: true,
    employerContribution: false,
    taxableImpact: 'post_tax_deduction',
    accountingImpact: 'employee_deduction',
    version: '1.0.0',
    effectiveFrom: '2025-03-01',
    payslipLabel: 'Union Fees',
  },
  {
    id: 'garnishee',
    name: 'Garnishee Order',
    category: 'deduction',
    enabledByDefault: false,
    companyConfigurable: true,
    employeeConfigurable: true,
    calculationOrder: 130,
    employeeContribution: true,
    employerContribution: false,
    taxableImpact: 'post_tax_deduction',
    accountingImpact: 'employee_deduction',
    version: '1.0.0',
    effectiveFrom: '2025-03-01',
    payslipLabel: 'Garnishee Order',
  },
  {
    id: 'custom_deduction',
    name: 'Custom Deduction',
    category: 'custom',
    enabledByDefault: false,
    companyConfigurable: true,
    employeeConfigurable: true,
    calculationOrder: 140,
    employeeContribution: true,
    employerContribution: false,
    taxableImpact: 'post_tax_deduction',
    accountingImpact: 'employee_deduction',
    version: '1.0.0',
    effectiveFrom: '2025-03-01',
    payslipLabel: 'Custom Deduction',
  },
  {
    id: 'custom_employer_contribution',
    name: 'Custom Employer Contribution',
    category: 'custom',
    enabledByDefault: false,
    companyConfigurable: true,
    employeeConfigurable: true,
    calculationOrder: 113,
    employeeContribution: false,
    employerContribution: true,
    taxableImpact: 'none',
    accountingImpact: 'employer_expense',
    version: '1.0.0',
    effectiveFrom: '2025-03-01',
    payslipLabel: 'Custom Employer Contribution',
  },
];

export function getRuleById(ruleId: string): PayrollRuleDefinition | undefined {
  return PAYROLL_RULE_CATALOG.find((r) => r.id === ruleId);
}

export function getSortedRules(): PayrollRuleDefinition[] {
  return [...PAYROLL_RULE_CATALOG].sort((a, b) => a.calculationOrder - b.calculationOrder);
}
