/**
 * VIP export branding — owned by the VIP audit module (V3.6.6).
 * Independent of the operational/platform export framework.
 */

import { BRAND } from '../../../config/brand';
import {
  VIP_CLASSIFICATION,
  VIP_REPORT_TITLE,
  VIP_SYSTEM_VERSION,
  type VipExportBranding,
  type VipWorkingPaperReport,
} from './types';

export function buildVipReportId(financialYearLabel: string): string {
  const now = new Date();
  const stamp = [
    now.getUTCFullYear(),
    String(now.getUTCMonth() + 1).padStart(2, '0'),
    String(now.getUTCDate()).padStart(2, '0'),
    String(now.getUTCHours()).padStart(2, '0'),
    String(now.getUTCMinutes()).padStart(2, '0'),
    String(now.getUTCSeconds()).padStart(2, '0'),
  ].join('');
  const fy = financialYearLabel.replace(/[^0-9A-Za-z]+/g, '').slice(0, 12);
  return ['ALF', 'VIP-WP', fy, stamp].filter(Boolean).join('-');
}

export function createVipExportBranding(input: {
  companyName: string;
  companyLogoUrl?: string | null;
  financialYear: string;
  payrollPeriod: string;
  generatedBy: string;
  report: VipWorkingPaperReport;
  generatedAt?: string;
  reportId?: string;
}): VipExportBranding {
  return {
    product: BRAND.product,
    platform: 'Enterprise Payroll Platform',
    reportTitle: VIP_REPORT_TITLE,
    companyName: input.companyName,
    companyLogoUrl: input.companyLogoUrl ?? null,
    financialYear: input.financialYear,
    payrollPeriod: input.payrollPeriod,
    generatedBy: input.generatedBy,
    generatedAt: input.generatedAt ?? new Date().toISOString(),
    reportId: input.reportId ?? buildVipReportId(input.financialYear),
    systemVersion: VIP_SYSTEM_VERSION,
    sourcePayrollRuns: input.report.sourcePayrollRunIds.join(', ') || '—',
    classification: VIP_CLASSIFICATION,
  };
}

export function assertVipBranding(branding: VipExportBranding | undefined): VipExportBranding {
  if (!branding) {
    throw new Error('VIP export branding is required. No VIP export may omit branding.');
  }
  if (!branding.companyName?.trim()) throw new Error('VIP branding.companyName is required.');
  if (!branding.reportId?.trim()) throw new Error('VIP branding.reportId is required.');
  if (!branding.generatedBy?.trim()) throw new Error('VIP branding.generatedBy is required.');
  return branding;
}

export function vipBrandingCsvPreamble(branding: VipExportBranding): string {
  const b = assertVipBranding(branding);
  return [
    `# ${b.product}`,
    `# ${b.platform}`,
    `# ${b.reportTitle}`,
    `# Company: ${b.companyName}`,
    `# Financial Year: ${b.financialYear}`,
    `# Payroll Period: ${b.payrollPeriod}`,
    `# Generated By: ${b.generatedBy}`,
    `# Generated: ${b.generatedAt}`,
    `# Report ID: ${b.reportId}`,
    `# System Version: ${b.systemVersion}`,
    `# Source Payroll Runs: ${b.sourcePayrollRuns}`,
    `# Classification: ${b.classification}`,
    `# System Generated`,
  ].join('\n') + '\n';
}

export const VIP_FOOTER_LINES = [
  `${BRAND.product} Enterprise Payroll Platform`,
  'Enterprise Payroll Working Paper',
  'System Generated Report',
  'Confidential',
] as const;
