/**
 * Default note ordering for presentation metadata (V14.2).
 * Lower sortOrder appears earlier in the notes section.
 */
export const DEFAULT_NOTE_ORDER: Record<string, number> = {
  'DISC.TRANSITION': 5,
  'DISC.GENERAL': 10,
  'DISC.BASIS': 20,
  'DISC.POLICIES': 30,
  'DISC.JUDGEMENTS': 40,
  'DISC.POLICYCHANGES': 45,
  'DISC.CONSOLIDATION': 50,
  'DISC.CAPITAL': 55,
  'DISC.REVENUE': 100,
  'DISC.GRANTS': 120,
  'DISC.REVENUE_NONEXCHANGE': 100,
  'DISC.REVENUE_EXCHANGE': 110,
  'DISC.DISCONTINUED': 150,
  'DISC.PPE': 200,
  'DISC.INTANGIBLES': 210,
  'DISC.INVPROP': 220,
  'DISC.BUSCOMB': 230,
  'DISC.HERITAGE': 230,
  'DISC.BIOLOGICAL': 240,
  'DISC.ASSOCIATES': 250,
  'DISC.JOINTVENTURES': 255,
  'DISC.IMPAIRMENT': 270,
  'DISC.INVENTORIES': 300,
  'DISC.RECEIVABLES': 310,
  'DISC.PAYABLES': 320,
  'DISC.FININST': 330,
  'DISC.LEASES': 340,
  'DISC.BORROWINGS': 350,
  'DISC.BORROWINGCOST': 355,
  'DISC.PROVISIONS': 400,
  'DISC.EMPLOYEE': 410,
  'DISC.SBP': 420,
  'DISC.TAX': 500,
  'DISC.DEFERREDTAX': 510,
  'DISC.FOREX': 520,
  'DISC.HYPERINFLATION': 530,
  'DISC.SHARECAPITAL': 600,
  'DISC.CASHFLOW': 700,
  'DISC.RELATED': 800,
  'DISC.COMMITMENTS': 850,
  'DISC.CONTINGENT': 860,
  'DISC.BUDGET': 870,
  'DISC.EVENTS': 900,
  'DISC.GOINGCONCERN': 950,
};

export function noteSortOrder(code: string): number {
  return DEFAULT_NOTE_ORDER[code] ?? 5000;
}
