/**
 * Compliance content — validate, lock and publish (ADR-0004, decision 7).
 *
 *   npm run compliance:content -- --check
 *       Validate the repository and print the stale-content report.
 *   npm run compliance:content -- --update-lock
 *       Recompute checksums.lock.json. Draft entries follow the text; a
 *       published or retired version whose text changed is refused.
 *   npm run compliance:content -- --sql [--include-drafts] > seed.sql
 *       Emit one idempotent SQL transaction that publishes the content.
 *       Apply it with: npx supabase db query --linked -f seed.sql
 *
 * Only reviewed ("published") rules are emitted by default. --include-drafts
 * also publishes draft rules, marked reviewed = false; the app then shows
 * that the guidance has not been reviewed yet. When a reviewer signs a draft
 * off, give it a new version number: a published version never changes.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { COMPLIANCE_CONTENT } from '../content/compliance/index';
import {
  canonicalJson,
  guidanceChecksum,
  lockKey,
  ruleChecksum,
  staleRules,
  updatedLock,
  validateContentRepository,
  type ChecksumLock,
  type RuleSource,
} from '../content/compliance/schema';

const LOCK_PATH = resolve(process.cwd(), 'content/compliance/checksums.lock.json');

function readLock(): ChecksumLock {
  try {
    return JSON.parse(readFileSync(LOCK_PATH, 'utf8')) as ChecksumLock;
  } catch {
    return {};
  }
}

const lit = (s: string | null | undefined) => (s === null || s === undefined ? 'NULL' : `'${s.replace(/'/g, "''")}'`);
const json = (v: unknown) => `${lit(canonicalJson(v))}::jsonb`;
const intArray = (a: number[]) => `'{${a.join(',')}}'::int[]`;

function ruleSql(rule: RuleSource, reviewed: boolean): string {
  const sum = ruleChecksum(rule);
  const key = `${rule.code} v${rule.version}`;
  const status = rule.status === 'retired' ? 'retired' : 'published';
  return `
-- ${key}
DO $check$
BEGIN
  IF EXISTS (
    SELECT 1 FROM public.compliance_rule_versions
    WHERE rule_code = ${lit(rule.code)} AND version = ${rule.version} AND checksum <> ${lit(sum)}
  ) THEN
    RAISE EXCEPTION '${key.replace(/'/g, "''")} is already published with different text; publish a new version.';
  END IF;
END;
$check$;

INSERT INTO public.compliance_rule_versions (
  rule_code, version, status, reviewed, country_code, category_code, industry_code, authority_code, title, summary,
  condition, schedule, evidence, priority, reminder_offsets, effective_from, effective_to, provenance, review_due, checksum
) VALUES (
  ${lit(rule.code)}, ${rule.version}, 'published', ${reviewed}, ${lit(rule.country_code)}, ${lit(rule.category_code)},
  ${lit(rule.industry_code)}, ${lit(rule.authority_code)}, ${lit(rule.title)}, ${lit(rule.summary)},
  ${json(rule.applies_when)}, ${json(rule.schedule)}, ${json(rule.evidence)}, ${lit(rule.priority)},
  ${intArray(rule.reminder_offsets)}, ${lit(rule.effective_from)}, ${lit(rule.effective_to)},
  ${json(rule.provenance)}, ${lit(rule.provenance.review_due)}, ${lit(sum)}
)
ON CONFLICT (rule_code, version) DO NOTHING;

INSERT INTO public.compliance_guidance_versions (rule_version_id, content, checksum)
SELECT id, ${json(rule.guidance)}, ${lit(guidanceChecksum(rule))}
FROM public.compliance_rule_versions WHERE rule_code = ${lit(rule.code)} AND version = ${rule.version}
ON CONFLICT (rule_version_id) DO NOTHING;
${status === 'retired'
    ? `
UPDATE public.compliance_rule_versions SET status = 'retired'
WHERE rule_code = ${lit(rule.code)} AND version = ${rule.version} AND status = 'published';`
    : ''}`;
}

function seedSql(includeDrafts: boolean): string {
  const repo = COMPLIANCE_CONTENT;
  const parts: string[] = [
    '-- Generated by scripts/complianceContentSeed.ts. Idempotent; safe to re-run.',
    `-- ${new Date().toISOString()}${includeDrafts ? ' (including unreviewed drafts)' : ''}`,
    'BEGIN;',
  ];
  for (const a of repo.authorities) {
    parts.push(
      `INSERT INTO public.compliance_authorities (code, name, country_code, website) VALUES (${lit(a.code)}, ${lit(a.name)}, ${lit(a.country_code)}, ${lit(a.website)})
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, country_code = EXCLUDED.country_code, website = EXCLUDED.website;`,
    );
  }
  for (const c of repo.categories) {
    parts.push(
      `INSERT INTO public.compliance_categories (code, name, sort_order) VALUES (${lit(c.code)}, ${lit(c.name)}, ${c.sort_order})
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order;`,
    );
  }
  for (const i of repo.industries) {
    parts.push(
      `INSERT INTO public.compliance_industries (code, name, active) VALUES (${lit(i.code)}, ${lit(i.name)}, ${i.active})
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, active = EXCLUDED.active;`,
    );
  }
  for (const [country, list] of Object.entries(repo.holidays)) {
    const values = list.map(([d, n]) => `(${lit(country)}, ${lit(d)}, ${lit(n)})`).join(',\n  ');
    parts.push(
      `INSERT INTO public.compliance_public_holidays (country_code, holiday_date, name) VALUES
  ${values}
ON CONFLICT (country_code, holiday_date) DO UPDATE SET name = EXCLUDED.name;`,
    );
  }
  let emitted = 0;
  for (const rule of repo.rules) {
    if (rule.status === 'draft' && !includeDrafts) continue;
    parts.push(ruleSql(rule, rule.status !== 'draft'));
    emitted += 1;
  }
  parts.push('COMMIT;');
  parts.push(`-- ${emitted} rule version(s) emitted.`);
  return parts.join('\n\n');
}

function main() {
  const args = new Set(process.argv.slice(2));
  const repo = COMPLIANCE_CONTENT;

  if (args.has('--update-lock')) {
    const lock = updatedLock(repo, readLock());
    writeFileSync(LOCK_PATH, `${JSON.stringify(lock, null, 2)}\n`);
    console.log(`Wrote ${Object.keys(lock).length} checksum(s) to content/compliance/checksums.lock.json`);
  }

  const problems = validateContentRepository(repo, readLock());
  if (problems.length) {
    console.error(`Compliance content is invalid:\n- ${problems.join('\n- ')}`);
    process.exit(1);
  }

  if (args.has('--sql')) {
    process.stdout.write(`${seedSql(args.has('--include-drafts'))}\n`);
    return;
  }

  const today = new Date().toISOString().slice(0, 10);
  const stale = staleRules(repo, today);
  const drafts = repo.rules.filter((r) => r.status === 'draft');
  console.log(`Compliance content is valid: ${repo.rules.length} rule version(s), ${drafts.length} awaiting review.`);
  for (const r of drafts) console.log(`  draft     ${lockKey(r)}  review due ${r.provenance.review_due}`);
  if (stale.length) {
    console.log(`Stale content (review date passed):`);
    for (const r of stale) console.log(`  STALE     ${lockKey(r)}  review was due ${r.provenance.review_due}`);
    if (args.has('--fail-on-stale')) process.exit(2);
  }
}

main();
