/**
 * Visual QA harness for payslip PDF layout.
 * Generates fixture PDFs + PNG previews for manual inspection.
 */
import { writeFileSync, mkdirSync, readFileSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { generatePayslipPdf } from '../src/lib/payrollDocuments';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');
const outDir = join(root, 'tmp', 'payslip-qa');
mkdirSync(outDir, { recursive: true });

function pngDataUrl(relPath: string): string {
  const abs = join(root, relPath);
  if (!existsSync(abs)) throw new Error(`Missing ${abs}`);
  return `data:image/png;base64,${readFileSync(abs).toString('base64')}`;
}

async function rasterize(pdfPath: string, prefix: string): Promise<string[]> {
  const { pdf } = await import('pdf-to-img');
  const paths: string[] = [];
  let n = 0;
  for await (const image of await pdf(pdfPath, { scale: 2 })) {
    n += 1;
    const pngPath = join(outDir, `${prefix}-page-${n}.png`);
    writeFileSync(pngPath, image);
    paths.push(pngPath);
  }
  return paths;
}

function baseFixture(companyLogoUrl: string | null) {
  return {
    companyName: 'Acme Manufacturing (Pty) Ltd',
    companyAddress: '12 Long Street\nCape Town CBD\nWestern Cape\n8001\nSouth Africa',
    companyTaxId: '9876543210',
    companyLogoUrl,
    employee: {
      first_name: 'Thabo',
      last_name: 'Molefe',
      employee_number: 'EMP-0042',
      department: 'Operations',
      tax_number: '9001015800083',
      bank_name: 'FNB',
      bank_account_number: '62000000001',
      bank_branch_code: '250655',
    },
    payPeriodStart: '2026-04-01',
    payPeriodEnd: '2026-04-30',
    payDate: '2026-04-25',
    items: [
      { description: 'Basic Salary', type: 'earning' as const, amount: 25000 },
      { description: 'Travel Allowance', type: 'earning' as const, amount: 2500 },
      { description: 'PAYE', type: 'deduction' as const, amount: 4200 },
      { description: 'UIF', type: 'deduction' as const, amount: 177.12 },
      { description: 'Medical Aid', type: 'deduction' as const, amount: 1800 },
      { description: 'UIF Employer', type: 'employer_contribution' as const, amount: 177.12 },
      { description: 'SDL', type: 'employer_contribution' as const, amount: 275 },
    ],
    total_earnings: 27500,
    total_deductions: 6177.12,
    net_pay: 21322.88,
    payment_method: 'EFT',
    bank_reference: 'PAY-2026-04-25',
    audit_reference: 'PSL-QAFIX01',
    payslip_id: 'qa-fix-001',
    payroll_run_id: 'run-qa-001',
    tax_year: '2025/2026',
    rule_version: '2025.2.0',
    calculation_version: '3.0.2',
  };
}

async function main() {
  const brandPng = pngDataUrl('public/icons/app-icon.png');

  // Case A: company logo provided (data URL — works offline)
  const withCompany = await generatePayslipPdf(baseFixture(brandPng));
  const withCompanyPath = join(outDir, 'payslip-company-logo.pdf');
  writeFileSync(withCompanyPath, Buffer.from(withCompany.output('arraybuffer')));
  const withCompanyPreviews = await rasterize(withCompanyPath, 'company-logo');

  // Case B: no company logo — employer name/address remain primary; AdminLess Fin only in footer
  const defaultBrand = await generatePayslipPdf(baseFixture(null));
  const defaultPath = join(outDir, 'payslip-default-brand.pdf');
  writeFileSync(defaultPath, Buffer.from(defaultBrand.output('arraybuffer')));
  const defaultPreviews = await rasterize(defaultPath, 'default-brand');

  // Text extraction structural checks on default brand PDF
  const buf = Buffer.from(defaultBrand.output('arraybuffer'));
  const asText = buf.toString('latin1');
  const checks = {
    deductionsHeaderIntact: /Deductions/.test(asText),
    amountHeaderIntact: /Amount/.test(asText),
    statutoryHeaderIntact: /Statutory/.test(asText),
    employerHeaderIntact: /Employer Contributions/.test(asText),
    brandFooter: /Generated by/.test(asText) && /AdminLess Fin/.test(asText),
    paymentSection: /Payment Information/.test(asText) || /Payment Method/.test(asText),
    fullAccount: /62000000001/.test(asText),
    branchCode: /250655/.test(asText),
    bankName: /FNB/.test(asText),
  };

  let extracted = '';
  try {
    const pdfjs = await import('pdfjs-dist/legacy/build/pdf.mjs');
    const pdf = await pdfjs.getDocument({ data: new Uint8Array(buf) }).promise;
    const page = await pdf.getPage(1);
    const content = await page.getTextContent();
    extracted = content.items.map((i) => ('str' in i ? i.str : '')).join(' ');
  } catch {
    // optional
  }

  const report = {
    withCompanyPath,
    withCompanyPreviews,
    defaultPath,
    defaultPreviews,
    checks,
    extractedPreview: extracted.slice(0, 600),
    noStackedDeductions: extracted ? !/D e d u c t i o n s/.test(extracted) : null,
  };
  writeFileSync(join(outDir, 'qa-report.json'), JSON.stringify(report, null, 2));
  console.log(JSON.stringify(report, null, 2));

  const failed = Object.entries(checks).filter(([, v]) => v === false);
  if (failed.length) throw new Error(`QA failed: ${failed.map(([k]) => k).join(', ')}`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
