/**
 * VIP-owned Excel export (V3.6.6) — independent of operational export framework.
 */

import { assertVipBranding } from '../branding';
import { VIP_LAYOUT } from '../layout';
import type { VipExportBranding, VipWorkingPaperReport } from '../types';
import { vipWorkingPaperToDetailRows } from '../builder';
import { VIP_ANNUAL_TOTAL_COLUMN } from '../types';

function escapeXml(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function triggerDownload(blob: Blob, fileName: string): void {
  if (typeof document === 'undefined') return;
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = fileName;
  a.click();
  URL.revokeObjectURL(url);
}

function cell(v: string | number): string {
  if (typeof v === 'number' && Number.isFinite(v)) {
    return `<Cell><Data ss:Type="Number">${v}</Data></Cell>`;
  }
  return `<Cell><Data ss:Type="String">${escapeXml(String(v ?? ''))}</Data></Cell>`;
}

function metaBlock(b: VipExportBranding): string {
  const pairs: [string, string][] = [
    ['Product', b.product],
    ['Platform', b.platform],
    ['Report', b.reportTitle],
    ['Company', b.companyName],
    ['Financial Year', b.financialYear],
    ['Payroll Period', b.payrollPeriod],
    ['Generated By', b.generatedBy],
    ['Generated', b.generatedAt],
    ['Report ID', b.reportId],
    ['System Version', b.systemVersion],
    ['Source Payroll Runs', b.sourcePayrollRuns],
    ['Classification', b.classification],
  ];
  return pairs
    .map(([k, v]) => `<Row>${cell(k)}${cell(v)}</Row>`)
    .join('\n');
}

function workingPaperSheet(report: VipWorkingPaperReport, branding: VipExportBranding): string {
  const b = assertVipBranding(branding);
  const rows: string[] = [metaBlock(b), '<Row></Row>'];

  for (const emp of report.employees) {
    rows.push(`<Row>${cell('EMPLOYEE INFORMATION')}</Row>`);
    for (const f of VIP_LAYOUT.identityFields) {
      rows.push(`<Row>${cell(f.label)}${cell(emp.identity[f.key])}</Row>`);
    }
    rows.push('<Row></Row>');

    const headerCells = ['Payroll Item', ...report.monthColumns, VIP_ANNUAL_TOTAL_COLUMN]
      .map((h) => cell(h))
      .join('');

    for (const block of emp.blocks) {
      if (block.id === 'employee_information') continue;
      rows.push(`<Row>${cell(block.title)}</Row>`);
      rows.push(`<Row>${headerCells}</Row>`);
      for (const line of block.lines) {
        const vals = [
          line.label,
          ...report.monthColumns.map((c) => line.months[c] ?? 0),
          line.annualTotal,
        ];
        rows.push(`<Row>${vals.map(cell).join('')}</Row>`);
      }
      rows.push('<Row></Row>');
    }
    rows.push('<Row></Row>');
  }

  const metaLines = 12;
  return `<Worksheet ss:Name="VIP Payroll Report">
  <Table>
${rows.join('\n')}
  </Table>
  <WorksheetOptions xmlns="urn:schemas-microsoft-com:office:excel">
    <PageSetup>
      <Layout x:Orientation="Landscape"/>
      <Header x:Margin="0.3"/>
      <Footer x:Margin="0.3"/>
      <PageMargins x:Bottom="0.5" x:Left="0.4" x:Right="0.4" x:Top="0.5"/>
    </PageSetup>
    <FreezePanes/>
    <FrozenNoSplit/>
    <SplitHorizontal>${metaLines}</SplitHorizontal>
    <TopRowBottomPane>${metaLines}</TopRowBottomPane>
    <ActivePane>2</ActivePane>
  </WorksheetOptions>
</Worksheet>`;
}

function detailSheet(report: VipWorkingPaperReport): string {
  const detail = vipWorkingPaperToDetailRows(report);
  if (detail.length === 0) {
    return `<Worksheet ss:Name="Detail"><Table></Table></Worksheet>`;
  }
  const headers = Object.keys(detail[0]);
  const headerRow = `<Row>${headers.map((h) => cell(h)).join('')}</Row>`;
  const body = detail
    .map((row) => `<Row>${headers.map((h) => cell(row[h] ?? '')).join('')}</Row>`)
    .join('\n');
  const lastRow = detail.length + 1;
  const lastCol = headers.length;
  return `<Worksheet ss:Name="Detail">
  <Table>
${headerRow}
${body}
  </Table>
  <AutoFilter x:Range="R1C1:R${lastRow}C${lastCol}" xmlns="urn:schemas-microsoft-com:office:excel"></AutoFilter>
  <WorksheetOptions xmlns="urn:schemas-microsoft-com:office:excel">
    <FreezePanes/>
    <FrozenNoSplit/>
    <SplitHorizontal>1</SplitHorizontal>
    <TopRowBottomPane>1</TopRowBottomPane>
    <ActivePane>2</ActivePane>
  </WorksheetOptions>
</Worksheet>`;
}

export function buildVipSpreadsheetMl(
  report: VipWorkingPaperReport,
  branding: VipExportBranding
): string {
  assertVipBranding(branding);
  return `<?xml version="1.0"?>
<?mso-application progid="Excel.Sheet"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
 xmlns:o="urn:schemas-microsoft-com:office:office"
 xmlns:x="urn:schemas-microsoft-com:office:excel"
 xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet">
 <DocumentProperties xmlns="urn:schemas-microsoft-com:office:office">
  <Title>Enterprise Payroll Working Paper</Title>
  <Subject>${escapeXml(branding.reportTitle)}</Subject>
  <Company>${escapeXml(branding.companyName)}</Company>
 </DocumentProperties>
 ${workingPaperSheet(report, branding)}
 ${detailSheet(report)}
</Workbook>`;
}

export function exportVipExcel(
  report: VipWorkingPaperReport,
  branding: VipExportBranding,
  fileBaseName: string
): { fileName: string; contentType: string; payload: string } {
  const payload = buildVipSpreadsheetMl(report, branding);
  const name = fileBaseName.endsWith('.xls') ? fileBaseName : `${fileBaseName}.xls`;
  if (typeof document !== 'undefined') {
    triggerDownload(new Blob([payload], { type: 'application/vnd.ms-excel' }), name);
  }
  return { fileName: name, contentType: 'application/vnd.ms-excel', payload };
}
