/**
 * VIP-owned PDF export (V3.6.6) — independent of operational export framework.
 */

import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { assertVipBranding, VIP_FOOTER_LINES } from '../branding';
import { VIP_LAYOUT } from '../layout';
import { VIP_ANNUAL_TOTAL_COLUMN, type VipExportBranding, type VipWorkingPaperReport } from '../types';

type JsPdfDoc = jsPDF & { lastAutoTable?: { finalY: number } };

async function tryLoadLogo(url: string | null | undefined): Promise<string | null> {
  if (!url || typeof fetch === 'undefined') return null;
  try {
    const res = await fetch(url);
    if (!res.ok) return null;
    const blob = await res.blob();
    return await new Promise((resolve) => {
      const reader = new FileReader();
      reader.onloadend = () => resolve(typeof reader.result === 'string' ? reader.result : null);
      reader.onerror = () => resolve(null);
      reader.readAsDataURL(blob);
    });
  } catch {
    return null;
  }
}

function drawHeader(doc: jsPDF, branding: VipExportBranding, logo: string | null): number {
  const b = assertVipBranding(branding);
  let y = 12;
  if (logo) {
    try {
      doc.addImage(logo, 'PNG', 14, 8, 18, 18);
    } catch {
      /* ignore */
    }
  }
  const left = logo ? 36 : 14;
  doc.setFontSize(10);
  doc.setTextColor(4, 120, 87);
  doc.text(b.product, left, y);
  y += 4.5;
  doc.setFontSize(8);
  doc.setTextColor(80);
  doc.text(b.platform, left, y);
  y += 5;
  doc.setFontSize(12);
  doc.setTextColor(0);
  doc.text(b.reportTitle, left, y);
  y += 6;
  doc.setFontSize(8);
  doc.setTextColor(50);
  const meta = [
    `Company: ${b.companyName}`,
    `Financial Year: ${b.financialYear}`,
    `Payroll Period: ${b.payrollPeriod}`,
    `Generated By: ${b.generatedBy}`,
    `Generated: ${b.generatedAt}`,
    `Report ID: ${b.reportId}`,
    `System Version: ${b.systemVersion}`,
    `Source Payroll Runs: ${b.sourcePayrollRuns}`,
    `Classification: ${b.classification} · System Generated`,
  ];
  for (const line of meta) {
    doc.text(line, left, y);
    y += 3.8;
  }
  doc.setTextColor(0);
  return y + 4;
}

function drawFooters(doc: jsPDF): void {
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    const h = doc.internal.pageSize.getHeight();
    const w = doc.internal.pageSize.getWidth();
    doc.setFontSize(7);
    doc.setTextColor(100);
    let fy = h - 16;
    for (const line of VIP_FOOTER_LINES) {
      doc.text(line, 14, fy);
      fy += 3.2;
    }
    doc.text(`Page ${i} of ${pageCount}`, w - 14, h - 8, { align: 'right' });
    doc.setTextColor(0);
  }
}

function exportVipPdfSync(
  report: VipWorkingPaperReport,
  branding: VipExportBranding,
  fileBaseName: string,
  logo: string | null
): { fileName: string; contentType: string } {
  const b = assertVipBranding(branding);
  const name = fileBaseName.endsWith('.pdf') ? fileBaseName : `${fileBaseName}.pdf`;
  if (typeof document === 'undefined') {
    return { fileName: name, contentType: 'application/pdf' };
  }

  const doc = new jsPDF({ orientation: 'landscape' }) as JsPdfDoc;

  report.employees.forEach((emp, idx) => {
    if (idx > 0) doc.addPage();
    let y = drawHeader(doc, b, logo);

    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.text('EMPLOYEE INFORMATION', 14, y);
    doc.setFont('helvetica', 'normal');
    y += 5;
    doc.setFontSize(8);
    for (const f of VIP_LAYOUT.identityFields) {
      doc.text(`${f.label}: ${emp.identity[f.key]}`, 14, y);
      y += 3.8;
    }
    y += 3;

    for (const block of emp.blocks) {
      if (block.id === 'employee_information') continue;
      if (y > doc.internal.pageSize.getHeight() - 40) {
        doc.addPage();
        y = drawHeader(doc, b, logo);
      }
      doc.setFontSize(9);
      doc.setFont('helvetica', 'bold');
      doc.text(block.title, 14, y);
      doc.setFont('helvetica', 'normal');
      y += 2;

      const headers = ['Payroll Item', ...report.monthColumns, VIP_ANNUAL_TOTAL_COLUMN];
      const body = block.lines.map((line) => [
        line.label,
        ...report.monthColumns.map((c) => String(line.months[c] ?? 0)),
        String(line.annualTotal),
      ]);

      autoTable(doc, {
        startY: y,
        head: [headers],
        body,
        styles: { fontSize: 6.5, cellPadding: 1.2 },
        headStyles: { fillColor: [4, 120, 87] },
        margin: { left: 14, right: 14 },
      });
      y = (doc.lastAutoTable?.finalY ?? y) + 8;
    }
  });

  if (report.employees.length === 0) {
    drawHeader(doc, b, logo);
    doc.setFontSize(10);
    doc.text('No finalized payroll facts for this tax year.', 14, 60);
  }

  drawFooters(doc);
  doc.save(name);
  return { fileName: name, contentType: 'application/pdf' };
}

export function exportVipPdf(
  report: VipWorkingPaperReport,
  branding: VipExportBranding,
  fileBaseName: string
): { fileName: string; contentType: string } {
  return exportVipPdfSync(report, branding, fileBaseName, null);
}

export async function exportVipPdfAsync(
  report: VipWorkingPaperReport,
  branding: VipExportBranding,
  fileBaseName: string
): Promise<{ fileName: string; contentType: string }> {
  const logo = await tryLoadLogo(branding.companyLogoUrl);
  return exportVipPdfSync(report, branding, fileBaseName, logo);
}
