import { escapeXml, triggerDownload } from '../download';
import {
  assertExportBranding,
  resolveBranding,
  type ExportSection,
  type ReportExportBranding,
} from '../branding';

function metaRows(branding: ReportExportBranding): string {
  const b = resolveBranding(branding);
  const pairs: [string, string][] = [
    ['Product', b.product],
    ['Company', b.companyName],
    ['Report', b.reportTitle],
  ];
  if (b.financialYear) pairs.push(['Financial Year', b.financialYear]);
  if (b.period) pairs.push(['Period', b.period]);
  pairs.push(['Generated By', b.generatedBy]);
  pairs.push(['Generated Date', b.generatedAt]);
  pairs.push(['Report ID', b.reportId]);
  if (b.companyLogoUrl) pairs.push(['Company Logo URL', b.companyLogoUrl]);

  return pairs
    .map(
      ([k, v]) =>
        `<Row><Cell><Data ss:Type="String">${escapeXml(k)}</Data></Cell><Cell><Data ss:Type="String">${escapeXml(v)}</Data></Cell></Row>`
    )
    .join('\n');
}

function tableRowsFromRecords(rows: Record<string, string | number>[]): {
  header: string;
  body: string;
  colCount: number;
} {
  if (rows.length === 0) {
    return { header: '', body: '', colCount: 0 };
  }
  const headers = Object.keys(rows[0]);
  const header = `<Row>${headers
    .map((h) => `<Cell><Data ss:Type="String">${escapeXml(h)}</Data></Cell>`)
    .join('')}</Row>`;
  const body = rows
    .map((row) => {
      const cells = headers
        .map((h) => {
          const raw = row[h];
          if (typeof raw === 'number' && Number.isFinite(raw)) {
            return `<Cell><Data ss:Type="Number">${raw}</Data></Cell>`;
          }
          return `<Cell><Data ss:Type="String">${escapeXml(String(raw ?? ''))}</Data></Cell>`;
        })
        .join('');
      return `<Row>${cells}</Row>`;
    })
    .join('\n');
  return { header, body, colCount: headers.length };
}

function sectionBlock(section: ExportSection): string {
  const identityXml = Object.entries(section.identity)
    .map(
      ([k, v]) =>
        `<Row><Cell><Data ss:Type="String">${escapeXml(k)}</Data></Cell><Cell><Data ss:Type="String">${escapeXml(v)}</Data></Cell></Row>`
    )
    .join('\n');
  const { header, body } = tableRowsFromRecords(section.rows);
  return `${identityXml}
${header}
${body}
<Row></Row>`;
}

function worksheetOptions(freezeRow: number): string {
  return `<WorksheetOptions xmlns="urn:schemas-microsoft-com:office:excel">
  <PageSetup>
   <Layout x:Orientation="Landscape"/>
   <Header x:Margin="0.3"/>
   <Footer x:Margin="0.3"/>
   <PageMargins x:Bottom="0.5" x:Left="0.4" x:Right="0.4" x:Top="0.5"/>
  </PageSetup>
  <Print>
   <ValidPrinterInfo/>
   <PaperSizeIndex>9</PaperSizeIndex>
   <FitWidth>1</FitWidth>
   <FitHeight>0</FitHeight>
  </Print>
  <FreezePanes/>
  <FrozenNoSplit/>
  <SplitHorizontal>${freezeRow}</SplitHorizontal>
  <TopRowBottomPane>${freezeRow}</TopRowBottomPane>
  <ActivePane>2</ActivePane>
 </WorksheetOptions>`;
}

/**
 * Build SpreadsheetML workbook. When branding is provided, emits Working Paper
 * (sectioned or flat + heading) and optional Detail sheet with AutoFilter.
 */
export function buildSpreadsheetMl(
  rows: Record<string, string | number>[],
  options?: {
    branding?: ReportExportBranding;
    sections?: ExportSection[];
    detailRows?: Record<string, string | number>[];
  }
): string {
  const branding = options?.branding;
  const sections = options?.sections;
  const detailRows = options?.detailRows ?? rows;

  if (!branding && (!sections || sections.length === 0) && rows.length === 0) {
    return `<?xml version="1.0"?><?mso-application progid="Excel.Sheet"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
 xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
 xmlns:x="urn:schemas-microsoft-com:office:excel">
 <Worksheet ss:Name="Report"><Table></Table></Worksheet>
</Workbook>`;
  }

  let workingPaperTable: string;
  let freezeRow = 1;

  if (branding && sections && sections.length > 0) {
    const meta = metaRows(branding);
    const metaLineCount = meta.split('\n').filter(Boolean).length;
    freezeRow = metaLineCount;
    const body = sections.map(sectionBlock).join('\n');
    workingPaperTable = `<Table>
${meta}
<Row></Row>
${body}
</Table>`;
  } else if (branding) {
    const meta = metaRows(branding);
    const metaLineCount = meta.split('\n').filter(Boolean).length;
    const { header, body } = tableRowsFromRecords(rows);
    workingPaperTable = `<Table>
${meta}
<Row></Row>
${header}
${body}
</Table>`;
    freezeRow = metaLineCount + 2;
  } else {
    const { header, body } = tableRowsFromRecords(rows);
    workingPaperTable = `<Table>
${header}
${body}
</Table>`;
  }

  const workingSheet = `<Worksheet ss:Name="${branding ? 'Working Paper' : 'Report'}">
  ${workingPaperTable}
  ${branding ? worksheetOptions(Math.max(1, freezeRow)) : ''}
 </Worksheet>`;

  let detailSheet = '';
  if (branding && detailRows.length > 0) {
    const { header, body, colCount } = tableRowsFromRecords(detailRows);
    const lastRow = detailRows.length + 1;
    const lastCol = Math.max(colCount, 1);
    detailSheet = `<Worksheet ss:Name="Detail">
  <Table>
${header}
${body}
  </Table>
  <AutoFilter x:Range="R1C1:R${lastRow}C${lastCol}" xmlns="urn:schemas-microsoft-com:office:excel"></AutoFilter>
  ${worksheetOptions(1)}
 </Worksheet>`;
  }

  return `<?xml version="1.0"?>
<?mso-application progid="Excel.Sheet"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
 xmlns:o="urn:schemas-microsoft-com:office:office"
 xmlns:x="urn:schemas-microsoft-com:office:excel"
 xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet">
 ${workingSheet}
 ${detailSheet}
</Workbook>`;
}

export function exportExcel(
  rows: Record<string, string | number>[],
  fileName: string,
  options?: {
    branding?: ReportExportBranding;
    sections?: ExportSection[];
    detailRows?: Record<string, string | number>[];
  }
): { fileName: string; contentType: string; payload: string } {
  // Browser (UI) exports must carry branding; Node/unit tests may omit for payload shape checks.
  if (typeof document !== 'undefined') {
    assertExportBranding(options?.branding, 'excel');
  } else if (options?.branding) {
    assertExportBranding(options.branding, 'excel');
  }

  const payload = buildSpreadsheetMl(rows, options);
  const name = fileName.endsWith('.xls') ? fileName : `${fileName}.xls`;
  if (typeof document !== 'undefined') {
    const blob = new Blob([payload], { type: 'application/vnd.ms-excel' });
    triggerDownload(blob, name);
  }
  return { fileName: name, contentType: 'application/vnd.ms-excel', payload };
}
