// ARCHITECTURE NOTE:
// This Supabase client is configured for client-side operations.
// As per our security architecture, direct database queries (e.g., supabase.from(...))
// are prohibited from the frontend. All database interactions must be routed through
// secure, server-side Supabase Edge Functions.
//
// You can, however, use this client for:
// - Authentication (supabase.auth)
// - Invoking Edge Functions (supabase.functions.invoke)
// - Interacting with Storage (supabase.storage)

// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://zaulhnpohrgqqodvzhxp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InphdWxobnBvaHJncXFvZHZ6aHhwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIzNDE2NzQsImV4cCI6MjA3NzkxNzY3NH0.ZtoBws6guJQBhxW789-YxdUVYwCF6CUDaW37ndCHFQU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);