/**
 * Enterprise report export branding — owned by the export framework (V3.6.5).
 * Individual reports supply data + metadata; they must not duplicate chrome.
 */

import { BRAND } from '../../config/brand';

export type ReportExportBranding = {
  /** Defaults to AdminLess Fin product name. */
  product?: string;
  companyName: string;
  companyLogoUrl?: string | null;
  reportTitle: string;
  financialYear?: string;
  period?: string;
  generatedBy: string;
  /** ISO timestamp; defaults to now when omitted. */
  generatedAt?: string;
  reportId: string;
  /** Defaults to AdminLess Fin system-generated footer. */
  footer?: string;
};

export type ExportSection = {
  /** Employee / section identity shown above the item table. */
  identity: Record<string, string>;
  rows: Record<string, string | number>[];
};

const DEFAULT_FOOTER = `${BRAND.product} — System Generated Report`;

export function resolveBranding(branding: ReportExportBranding): Required<
  Pick<
    ReportExportBranding,
    'product' | 'companyName' | 'reportTitle' | 'generatedBy' | 'generatedAt' | 'reportId' | 'footer'
  >
> &
  ReportExportBranding {
  return {
    ...branding,
    product: branding.product ?? BRAND.product,
    generatedAt: branding.generatedAt ?? new Date().toISOString(),
    footer: branding.footer ?? DEFAULT_FOOTER,
  };
}

/**
 * Build a stable-ish report id for exports.
 * Example: ALF-VIP-2026-20260713114530
 */
export function buildReportId(reportCode: string, financialYearLabel?: string): string {
  const now = new Date();
  const stamp = [
    now.getUTCFullYear(),
    String(now.getUTCMonth() + 1).padStart(2, '0'),
    String(now.getUTCDate()).padStart(2, '0'),
    String(now.getUTCHours()).padStart(2, '0'),
    String(now.getUTCMinutes()).padStart(2, '0'),
    String(now.getUTCSeconds()).padStart(2, '0'),
  ].join('');
  const short = reportCode
    .replace(/^payroll\./, '')
    .replace(/[^a-zA-Z0-9]+/g, '-')
    .replace(/^-|-$/g, '')
    .toUpperCase()
    .slice(0, 24);
  const fy = financialYearLabel
    ? financialYearLabel.replace(/[^0-9A-Za-z]+/g, '').slice(0, 12)
    : '';
  return ['ALF', short, fy, stamp].filter(Boolean).join('-');
}

/** CSV metadata preamble lines (comment-style). */
export function brandingToCsvPreamble(branding: ReportExportBranding): string {
  const b = resolveBranding(branding);
  const lines = [
    `# Product: ${b.product}`,
    `# Company: ${b.companyName}`,
    `# Report: ${b.reportTitle}`,
    b.financialYear ? `# Financial Year: ${b.financialYear}` : null,
    b.period ? `# Period: ${b.period}` : null,
    `# Generated By: ${b.generatedBy}`,
    `# Generated Date: ${b.generatedAt}`,
    `# Report ID: ${b.reportId}`,
    `# Footer: ${b.footer}`,
  ].filter(Boolean) as string[];
  return lines.join('\n') + '\n';
}

export function assertExportBranding(
  branding: ReportExportBranding | undefined,
  format: string
): ReportExportBranding {
  if (!branding) {
    throw new Error(
      `Export branding is required for ${format} exports. Pass ReportExportBranding via the export framework.`
    );
  }
  if (!branding.companyName?.trim()) {
    throw new Error('Export branding.companyName is required.');
  }
  if (!branding.reportTitle?.trim()) {
    throw new Error('Export branding.reportTitle is required.');
  }
  if (!branding.generatedBy?.trim()) {
    throw new Error('Export branding.generatedBy is required.');
  }
  if (!branding.reportId?.trim()) {
    throw new Error('Export branding.reportId is required.');
  }
  return branding;
}
