// Type-only: erased at build time, so this creates no runtime dependency on
// jsPDF. The engine is fetched on demand via loadPdfEngine() — see
// src/lib/pdf/pdfEngine.ts for why.
import type jsPDF from 'jspdf';
import { loadPdfEngine } from '../../../lib/pdf/pdfEngine';
import { BRAND } from '../../../config/brand';
import {
  assertExportBranding,
  resolveBranding,
  type ExportSection,
  type ReportExportBranding,
} from '../branding';

type JsPdfWithAutoTable = jsPDF & { lastAutoTable?: { finalY: number } };

async function tryLoadLogoDataUrl(url: string | null | undefined): Promise<string | null> {
  if (!url || typeof fetch === 'undefined') return null;
  try {
    const res = await fetch(url);
    if (!res.ok) return null;
    const blob = await res.blob();
    return await new Promise((resolve) => {
      const reader = new FileReader();
      reader.onloadend = () => resolve(typeof reader.result === 'string' ? reader.result : null);
      reader.onerror = () => resolve(null);
      reader.readAsDataURL(blob);
    });
  } catch {
    return null;
  }
}

function drawBrandedHeader(
  doc: jsPDF,
  branding: ReportExportBranding,
  logoDataUrl: string | null
): number {
  const b = resolveBranding(branding);
  let y = 14;

  if (logoDataUrl) {
    try {
      doc.addImage(logoDataUrl, 'PNG', 14, 8, 22, 22);
    } catch {
      // ignore unsupported image formats
    }
  }

  const left = logoDataUrl ? 40 : 14;
  doc.setFontSize(11);
  doc.setTextColor(4, 120, 87);
  doc.text(b.product, left, y);
  doc.setTextColor(0);
  y += 6;
  doc.setFontSize(14);
  doc.text(b.reportTitle, left, y);
  y += 6;
  doc.setFontSize(9);
  doc.setTextColor(60);
  const meta: string[] = [`Company: ${b.companyName}`];
  if (b.financialYear) meta.push(`Financial Year: ${b.financialYear}`);
  if (b.period) meta.push(`Period: ${b.period}`);
  meta.push(`Generated By: ${b.generatedBy}`);
  meta.push(`Generated Date: ${b.generatedAt}`);
  meta.push(`Report ID: ${b.reportId}`);
  for (const line of meta) {
    doc.text(line, left, y);
    y += 4.5;
  }
  doc.setTextColor(0);
  return y + 4;
}

function drawFooters(doc: jsPDF, branding: ReportExportBranding): void {
  const b = resolveBranding(branding);
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    const h = doc.internal.pageSize.getHeight();
    const w = doc.internal.pageSize.getWidth();
    doc.setFontSize(8);
    doc.setTextColor(100);
    doc.text(b.footer, 14, h - 8);
    doc.text(`Page ${i} of ${pageCount}`, w - 14, h - 8, { align: 'right' });
    doc.setTextColor(0);
  }
}

function writeIdentityBlock(doc: jsPDF, identity: Record<string, string>, startY: number): number {
  let y = startY;
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.text('Employee', 14, y);
  doc.setFont('helvetica', 'normal');
  y += 5;
  doc.setFontSize(9);
  for (const [k, v] of Object.entries(identity)) {
    doc.text(`${k}: ${v}`, 14, y);
    y += 4.2;
  }
  return y + 2;
}

/**
 * Renders and saves the PDF. Async only because the engine is now fetched on
 * demand; the drawing logic, page layout and output bytes are unchanged.
 * Note the non-browser early return below still happens *before* the engine is
 * requested, so Node/unit contexts never download it.
 */
async function renderPdf(
  rows: Record<string, string | number>[],
  options: {
    fileName: string;
    branding: ReportExportBranding;
    sections?: ExportSection[];
    logoDataUrl?: string | null;
  }
): Promise<{ fileName: string; contentType: string }> {
  const branding = assertExportBranding(options.branding, 'pdf');
  const name = options.fileName.endsWith('.pdf') ? options.fileName : `${options.fileName}.pdf`;
  if (typeof document === 'undefined') {
    return { fileName: name, contentType: 'application/pdf' };
  }

  const { jsPDF, autoTable } = await loadPdfEngine();

  const wide =
    (options.sections?.[0]?.rows[0] && Object.keys(options.sections[0].rows[0]).length > 6) ||
    (rows[0] && Object.keys(rows[0]).length > 6);

  const doc = new jsPDF({ orientation: wide ? 'landscape' : 'portrait' }) as JsPdfWithAutoTable;
  let y = drawBrandedHeader(doc, branding, options.logoDataUrl ?? null);

  if (options.sections && options.sections.length > 0) {
    options.sections.forEach((section, idx) => {
      if (idx > 0) {
        doc.addPage();
        y = drawBrandedHeader(doc, branding, options.logoDataUrl ?? null);
      }
      y = writeIdentityBlock(doc, section.identity, y);
      const headers = section.rows.length > 0 ? Object.keys(section.rows[0]) : ['(empty)'];
      const body = section.rows.map((row) => headers.map((h) => String(row[h] ?? '')));
      autoTable(doc, {
        startY: y,
        head: [headers],
        body,
        styles: { fontSize: 7, cellPadding: 1.5 },
        headStyles: { fillColor: [4, 120, 87] },
        margin: { left: 14, right: 14 },
      });
      y = (doc.lastAutoTable?.finalY ?? y) + 8;
    });
  } else {
    const headers = rows.length > 0 ? Object.keys(rows[0]) : ['(empty)'];
    const body = rows.map((row) => headers.map((h) => String(row[h] ?? '')));
    autoTable(doc, {
      startY: y,
      head: [headers],
      body,
      styles: { fontSize: 7, cellPadding: 1.5 },
      headStyles: { fillColor: [4, 120, 87] },
      margin: { left: 14, right: 14 },
    });
  }

  drawFooters(doc, branding);
  doc.save(name);
  return { fileName: name, contentType: 'application/pdf' };
}

/**
 * Branded PDF export. Supports flat rows or employee sections (VIP working paper).
 * Logo load is best-effort; falls back to AdminLess Fin wordmark text in the header.
 */
export async function exportPdf(
  rows: Record<string, string | number>[],
  options: {
    fileName: string;
    title?: string;
    subtitle?: string;
    branding?: ReportExportBranding;
    sections?: ExportSection[];
  }
): Promise<{ fileName: string; contentType: string }> {
  // Legacy title/subtitle path only allowed in non-browser (unit) contexts without branding
  if (!options.branding) {
    if (typeof document === 'undefined') {
      const name = options.fileName.endsWith('.pdf') ? options.fileName : `${options.fileName}.pdf`;
      return { fileName: name, contentType: 'application/pdf' };
    }
    assertExportBranding(options.branding, 'pdf');
  }

  const branding =
    options.branding ??
    ({
      companyName: '—',
      reportTitle: options.title ?? 'Report',
      generatedBy: BRAND.product,
      reportId: 'LEGACY',
      period: options.subtitle,
    } satisfies ReportExportBranding);

  return renderPdf(rows, {
    fileName: options.fileName,
    branding,
    sections: options.sections,
    logoDataUrl: null,
  });
}

/** Async PDF with optional company logo fetch (browser). */
export async function exportPdfAsync(
  rows: Record<string, string | number>[],
  options: {
    fileName: string;
    branding: ReportExportBranding;
    sections?: ExportSection[];
  }
): Promise<{ fileName: string; contentType: string }> {
  const branding = assertExportBranding(options.branding, 'pdf');
  const logoDataUrl = await tryLoadLogoDataUrl(branding.companyLogoUrl);
  return renderPdf(rows, {
    fileName: options.fileName,
    branding,
    sections: options.sections,
    logoDataUrl,
  });
}
